run tests

diff --git a/.azure-pipelines/unix-build.yml b/.azure-pipelines/unix-build.yml
--- a/.azure-pipelines/unix-build.yml
+++ b/.azure-pipelines/unix-build.yml
@@ -133,86 +133,86 @@ steps:
   displayName: DIALS build (initial)
   workingDirectory: $(Pipeline.Workspace)
   condition: eq(variables.BUILD_CACHED, 'false')
-  
-##  If the build directory was loaded (or kick-started) from cache then
-##  do an incremental build
-#-  bash: |
-#     set -e
-#     cp -v build/activate dials  # restore copy from the cache
-#     . dials
-#     cd build
-#     make reconf
-#   displayName: DIALS build (incremental)
-#   workingDirectory: $(Pipeline.Workspace)
-#   condition: ne(variables.BUILD_CACHED, 'false')
-#  
-##  Ensure we are using up-to-date testing packages.
-##  Extract the dials-data version so we can correctly cache regression data.
-#-  bash: |
-#     set -e
-#     . dials
-#     conda install -p conda_base -y dials-data pytest-azurepipelines pytest-cov pytest-timeout
-#     dials.data info -v
-#     echo "##vso[task.setvariable variable=DIALS_DATA_VERSION_FULL]$(dials.data info -v | grep version.full)"
-#     echo "##vso[task.setvariable variable=DIALS_DATA_VERSION]$(dials.data info -v | grep version.major)"
-#     #                                                                this is a bug in dials-data ^^^^^
-#     mkdir -p data
-#   displayName: Install additional packages
-#   workingDirectory: $(Pipeline.Workspace)
-#  
-##  Retrieve the regression data from cache if possible
-##  The cache allows day-to-day incremental updates, which is relevant only if
-##  tests are added that refer to datasets in dials-data that were not previously
-##  referred to.
-##  New versions of dials-data also lead to cache updates, kick-started from the
-##  previous cache version.
-##  The cache is shared across operating systems and python versions, and flushed
-##  once a week and for dials-data major and minor releases (eg. 2.0->2.1).
-#-  task: Cache@2
-#   inputs:
-#     key: '"data" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(DIALS_DATA_VERSION)" | "$(TODAY_ISO)" | "$(DIALS_DATA_VERSION_FULL)"'
-#     restoreKeys: |
-#       "data" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(DIALS_DATA_VERSION)" | "$(TODAY_ISO)"
-#       "data" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(DIALS_DATA_VERSION)"
-#     path: $(Pipeline.Workspace)/data
-#     cacheHitVar: DATA_CACHED
-#   displayName: Restore regression data cache
-#  
-##  Finally, run the full regression test suite
-#-  bash: |
-#     set -e
-#     export DIALS_DATA=$(pwd)/data
-#     . dials
-#     cd modules/dials
-#     pytest -v -ra -n auto --basetemp="$(Pipeline.Workspace)/tests" --durations=10 \
-#         --cov=$(pwd) --cov-report=html --cov-report=xml --cov-branch \
-#         --timeout=5400 --regression --runslow || echo "##vso[task.complete result=Failed;]Some tests failed"
-#   displayName: Run tests
-#   workingDirectory: $(Pipeline.Workspace)
-#  
+
+# If the build directory was loaded (or kick-started) from cache then
+# do an incremental build
+- bash: |
+    set -e
+    cp -v build/activate dials  # restore copy from the cache
+    . dials
+    cd build
+    make reconf
+  displayName: DIALS build (incremental)
+  workingDirectory: $(Pipeline.Workspace)
+  condition: ne(variables.BUILD_CACHED, 'false')
+
+# Ensure we are using up-to-date testing packages.
+# Extract the dials-data version so we can correctly cache regression data.
+- bash: |
+    set -e
+    . dials
+    conda install -p conda_base -y dials-data pytest-azurepipelines pytest-cov pytest-timeout
+    dials.data info -v
+    echo "##vso[task.setvariable variable=DIALS_DATA_VERSION_FULL]$(dials.data info -v | grep version.full)"
+    echo "##vso[task.setvariable variable=DIALS_DATA_VERSION]$(dials.data info -v | grep version.major)"
+    #                                                                this is a bug in dials-data ^^^^^
+    mkdir -p data
+  displayName: Install additional packages
+  workingDirectory: $(Pipeline.Workspace)
+
+# Retrieve the regression data from cache if possible
+# The cache allows day-to-day incremental updates, which is relevant only if
+# tests are added that refer to datasets in dials-data that were not previously
+# referred to.
+# New versions of dials-data also lead to cache updates, kick-started from the
+# previous cache version.
+# The cache is shared across operating systems and python versions, and flushed
+# once a week and for dials-data major and minor releases (eg. 2.0->2.1).
+- task: Cache@2
+  inputs:
+    key: '"data" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(DIALS_DATA_VERSION)" | "$(TODAY_ISO)" | "$(DIALS_DATA_VERSION_FULL)"'
+    restoreKeys: |
+      "data" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(DIALS_DATA_VERSION)" | "$(TODAY_ISO)"
+      "data" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(DIALS_DATA_VERSION)"
+    path: $(Pipeline.Workspace)/data
+    cacheHitVar: DATA_CACHED
+  displayName: Restore regression data cache
+
+# Finally, run the full regression test suite
+- bash: |
+    set -e
+    export DIALS_DATA=$(pwd)/data
+    . dials
+    cd modules/xia2
+    pytest -v -ra -n auto --basetemp="$(Pipeline.Workspace)/tests" --durations=10 \
+        --cov=$(pwd) --cov-report=html --cov-report=xml --cov-branch \
+        --timeout=5400 --regression-full || echo "##vso[task.complete result=Failed;]Some tests failed"
+  displayName: Run tests
+  workingDirectory: $(Pipeline.Workspace)
+
 #-  script: |
 #     bash <(curl -s https://codecov.io/bash) -n "Python $(PYTHON_VERSION) $(Agent.OS)"
 #   displayName: 'Publish coverage stats'
 #   continueOnError: True
 #   timeoutInMinutes: 3
 #   workingDirectory: $(Pipeline.Workspace)/modules/dials
-#  
-##  Recover disk space after testing
-##  This is only relevant if we had cache misses, as free disk space is required to create cache archives
-#-  bash: |
-#     echo Disk space usage:
-#     df -h
-#     du -sh *
-#     echo
-#     echo Test artefacts:
-#     du -h tests
-#     rm -rf tests
-#   displayName: Recover disk space
-#   workingDirectory: $(Pipeline.Workspace)
-#   condition: or(ne(variables.BASE_CACHED, 'true'),
-#                 ne(variables.BUILD_CACHED, 'true'),
-#                 ne(variables.DATA_CACHED, 'true'),
-#                 ne(variables.REPOSITORIES_CACHED, 'true'))
+
+# Recover disk space after testing
+# This is only relevant if we had cache misses, as free disk space is required to create cache archives
+- bash: |
+    echo Disk space usage:
+    df -h
+    du -sh *
+    echo
+    echo Test artefacts:
+    du -h tests
+    rm -rf tests
+  displayName: Recover disk space
+  workingDirectory: $(Pipeline.Workspace)
+  condition: or(ne(variables.BASE_CACHED, 'true'),
+                ne(variables.BUILD_CACHED, 'true'),
+                ne(variables.DATA_CACHED, 'true'),
+                ne(variables.REPOSITORIES_CACHED, 'true'))
 
 # If the downloaded repositories are to be cached then clean them up before the
 # snapshot is made
