Allow newsfragments Action to rename any sequence [xX]+ (#550)
Also, handle case where rename would cause conflict

diff --git a/.github/workflows/newsfragments.yml b/.github/workflows/newsfragments.yml
--- a/.github/workflows/newsfragments.yml
+++ b/.github/workflows/newsfragments.yml
@@ -31,15 +31,20 @@ jobs:
           fi
       - name: Rename placeholder newsfragments
         run: |
-          if ls newsfragments/XXX.* 1> /dev/null 2>&1; then
+          rename_candidates="$(find newsfragments -regex 'newsfragments/[xX]+\..*')"
+          if [[ -n "$rename_candidates" ]]; then
             git config user.name "DiamondLightSource-build-server"
             git config user.email "DiamondLightSource-build-server@users.noreply.github.com"
             HEAD_REPO="${{github.event.pull_request.head.repo.full_name}}"
             HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
             message=""
             git remote add fork https://x-access-token:${USER_TOKEN}@github.com/$HEAD_REPO.git
-            for fragment in newsfragments/XXX.*; do
-              target_file="$(echo "${fragment}" | sed "s/XXX/${{github.event.number}}/")"
+            for fragment in ${rename_candidates}; do
+              target_file="$(echo "${fragment}" | sed -E "s/[xX]+/${{github.event.number}}/")"
+              if [[ -f "${target_file}" ]]; then
+                echo "::error ::Cannot rename ${fragment} to ${target_file} as it already exists. Merge manually."
+                exit 1
+              fi
               git mv $fragment $target_file
               git add $target_file
               if [[ -z "${message}" ]]; then
